name: Playwright Tests

on:
  push:
    branches: ["main"]
    paths:
      - "e2e/js/**"
  pull_request:
    branches: ["main"]
    paths:
      - "e2e/js/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e/js

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: e2e/js/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run playwright tests
        run: npm test
